// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAppCleanArchitecture.Infrastructure;

#nullable disable

namespace TaskAppApi.Migrations
{
    [DbContext(typeof(TachesDbContext))]
    partial class TachesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskAppCleanArchitecture.Domaine.Models.TacheDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idTacheStatut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idTacheStatut");

                    b.ToTable("Taches");
                });

            modelBuilder.Entity("TaskAppCleanArchitecture.Domaine.Models.TacheStatut", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("statut")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TacheStatuts");
                });

            modelBuilder.Entity("TaskAppCleanArchitecture.Domaine.Models.TacheDo", b =>
                {
                    b.HasOne("TaskAppCleanArchitecture.Domaine.Models.TacheStatut", "TacheStatut")
                        .WithMany("TacheDo")
                        .HasForeignKey("idTacheStatut")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TacheStatut");
                });

            modelBuilder.Entity("TaskAppCleanArchitecture.Domaine.Models.TacheStatut", b =>
                {
                    b.Navigation("TacheDo");
                });
#pragma warning restore 612, 618
        }
    }
}
